## Python - Level 1 Exercises

#### Author: André Areosa
#### Date: 04/10/2022

### 1. Create a program that:
    a. asks a user the radius of a cylinder;
    b. asks a user the height of a cylinder;
    c. Prints the volume of that cylinder;
    d. Prints the surface area of that cylinder;

In [17]:
import math

def ask_cylinder():
    
    r = ''
    h = ''

    while not (type(r) == float and type(h) == float):
    
        try:
            r = float(input('Provide the radius for a cylinder: '))
            h = float(input('Provide the height for a cylinder: '))
    
        except:
            print('Please provide a valid entry!')
    
        else:
            print('Thank you!')
            print('Volume of the cylinder: ', + round(h * math.pi * r**2,2))
            print('Surface area of the cylinder: ', + round(2 * math.pi * r * (r + h),2))

In [18]:
ask_cylinder()

Provide the radius for a cylinder: 10
Provide the height for a cylinder: 5
Thank you!
Volume of the cylinder:  1570.8
Surface area of the cylinder:  942.48


### 2. Create a function that:

    a. Receives a string:
    b. print only the characters present at an even index number. (Eg.: ‘My string’ -> ‘M’, ‘ ’, ‘t’,’i’,’g’)

In [72]:
def even_string(some_string):
    
    even_chars = []
    
    for index,letter in enumerate(some_string):
        if index % 2 == 0:
            even_chars.append(letter)
            
    return even_chars

In [73]:
even_string('some random string')

['s', 'm', ' ', 'a', 'd', 'm', 's', 'r', 'n']

### 3. Create a function that:

    a. Receives an integer number
    b. Returns true if the given number is palindromic (eg.: 7, 77, 121,3443,5341435).


In [75]:
def ask_int():
    
    x = ''
    
    while not (type(x) == int):
        
        try:
            x = int(input('Provide a number to check if it is palindromic: '))
            
        except:
            print('Please provide a valid number!')
            
        else:
            return int(str(x)[::-1]) == x
            

In [74]:
ask_int()

Provide a number to check if it is palindromic: 3443


True

### 4. Using print(), format a decimal number to be displayed:

    a. With 2 decimal places (eg.: 123.456 -> 123.46);
    b. With 2 decimal places in exponential format (eg.: 123.456 ->1.23e+02).

In [102]:
from random import uniform

x = uniform(10,5000)
x

3559.196654469631

In [103]:
print('{:0.2f}'.format(x))

3559.20


In [111]:
print('{:.2e}'.format(x))

3.56e+03


### 5. Create a list of float numbers:
    
    a. ask the user for the list size;
    b. ask the user for each of the elements, individually;
    c. return the list.

In [5]:
def float_list():

    x = ''
    float_list = []

    while not (type(x) == int):
        
        try:
            x = int(input('Please provide a list size of your choice: '))
    
        except:
            print('Please provide a valid size list size!')
        
        else:
            print('Thank you! Now you have to select the elements individually')
        
    
    for i in range(x):
        
        float_list.append(float(input(f'For element {i} provide a float number to add: ')))
                 
    return float_list

In [6]:
float_list()

Please provide a list size of your choice: no
Please provide a valid size list size!
Please provide a list size of your choice: 5
Thank you! Now you have to select the elements individually
For element 0 provide a float number to add: 1.5
For element 1 provide a float number to add: 2
For element 2 provide a float number to add: 3.5
For element 3 provide a float number to add: 4.1
For element 4 provide a float number to add: 5


[1.5, 2.0, 3.5, 4.1, 5.0]

### 6. Create a program that:
    
    a. reads a file (txt file) containing more than 10 rows;
    b. creates a new file which excludes the 10th row of the original one.

In [94]:
with open('file.txt') as read_file:
    content = read_file.readlines()
    
content

['line 1 \n',
 'line 2\n',
 'line 3\n',
 'line 4\n',
 'line 5\n',
 'line 6\n',
 'line 7\n',
 'line 8\n',
 'line 9\n',
 'line 10\n',
 'line 11']

In [98]:
def file_reader(file):

    with open(file) as read_file:
        content = read_file.readlines()
        
    content_list = []
    
    for a,b in enumerate(content):
        if a < 9:
            content_list.append(b)
            
    new_file = open('new_file.txt',mode='w+')
    new_file.writelines(content_list)
    
    print('A new file called new_file.txt has been created excluding the 10th row of the original file')

In [99]:
file_reader('file.txt')

A new file called new_file.txt has been created excluding the 10th row of the original file


In [101]:
with open ('new_file.txt') as read_new_file:
    content_new_file = read_new_file.readlines()

#prove that the 10th row of the original files was indeed excluded
len(content_new_file)


9

### 7. Given and integer number, use a loop to find its factorial.

In [118]:
def give_factorial():

    x = ''
    
    while not (type(x) == int):
        
        try:
            x = int(input('Provide an integer number to find its factorial: '))

        except:
            print('Please provide an integer number!')
            
        
    factorial = 1

    for n in range(x+1):
        if n != 0:
            factorial = n * factorial
            
    return factorial

In [119]:
give_factorial()

Provide an integer number to find its factorial: no
Please provide an integer number!
Provide an integer number to find its factorial: 5


120

### 8. Using numpy library, create an array with values from 100 to 1000 with step=50,having 6 rows and 3 columns.

In [266]:
import numpy as np

np.arange(100,1000,50).reshape(6,3)

array([[100, 150, 200],
       [250, 300, 350],
       [400, 450, 500],
       [550, 600, 650],
       [700, 750, 800],
       [850, 900, 950]])

### 9. Sum arrays [[1, 2, 3], [10 , 10, 10]] and [[4, 2, 3], [1 ,1, 10]] and, then, create a newarray containing the square of each element

In [289]:
x = np.array([[1,2,3],[10,10,10]])
y = np.array([[4,2,3],[1,1,10]])

squared_elements = []

for x in np.add(x,y):
    squared_elements.append(x**2)
    
print(np.array(squared_elements))

[[ 25  16  36]
 [121 121 400]]


### 10. Consider array [[1,2,3],[4,5,6],[7,8,9]], delete its second column and insert [[99,99,99]] on its place.


In [303]:
z = np.array([[1,2,3],[4,5,6],[7,8,9]])
z[-2] = [99,99,99]
print(z)

[[ 1  2  3]
 [99 99 99]
 [ 7  8  9]]


### 11. Check if a string contains a ‘x’ followed by one or more ‘y’.

In [141]:
import re

def string_check(some_string):
    
    pattern = '\Dxy+'

    r = re.search(pattern,some_string)
    
    if r is not None:
        print('Check')
    
    else:
        print("There is no 'x' followed by one or more 'y'")
    

In [145]:
string_check('Check the foxy song')

Check


In [146]:
string_check('Check the fox song')

There is no 'x' followed by one or more 'y'


### 12. Create a function that:
    a - receives an IP address and returns a list with both: original IP, original IP without its leading zeros (eg.:'128.005.055.190', '128.5.55.190']).

In [242]:
def clean_ip(ip):
    
    ip_list = []
    
    for x in ip.split('.'):
        ip_list.append(int(x))
    
    clean_ip = [str(x) for x in ip_list]
    
    ips_list = [ip,('.'.join(clean_ip))]
    
    return ips_list

In [243]:
clean_ip('128.005.055.190')

['128.005.055.190', '128.5.55.190']

### 13. Create a program that:
    
    a. Asks the user to write a sequence of words split by commas;
    b. Prints that list sorted alphabetically. (Eg.: a,c,b -> [a,b,c])

In [260]:
def sorted_sequence():
    
    sequence = input('Write a sequence of words split by commas: ')
    
    return sorted(sequence.split(','))

In [262]:
sorted_sequence()

Write a sequence of words split by commas: shelby,andre,porto,braga,zambia


['andre', 'braga', 'porto', 'shelby', 'zambia']